server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///train
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: "HDU-Train-Ticket"




